name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Publish App
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn run publish
